export { ScdsGenerator } from './ScdsGenerator';
export type {
    Course,
    Module,
    NarrativeHook,
    Quiz,
    QuizQuestion,
    PodcastScript,
    PodcastSpeaker,
    PodcastSegment,
    ComicScript,
    ComicPanel,
    ComicDialogue,
    ComicCharacter,
    MindMap,
    MindMapNode,
    MindMapEdge,
    ChapterExtract,
    IngestionResult,
    CourseMetadata,
} from './types';
export {
    SYSTEM_PROMPTS,
    narrativePrompt,
    quizPrompt,
    podcastPrompt,
    comicPrompt,
    mindMapPrompt,
    comicPanelImagePrompt,
    avatarPartPrompt,
    buildingSpritePrompt,
    eraBackgroundPrompt,
    droidEvolutionPrompt,
} from './prompts';
